name: Docker Image CI

on:
  push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # - uses: actions/checkout@v4

    - 
      name: Read version from file
      id: get_version
      run: echo "VER=$(cat VERSION)" >> $GITHUB_ENV

    - 
      name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - 
      name: Build and push Docker images
      uses: docker/build-push-action@v6.10.0

      with:
        context: .
        push: true
        # tags: user/app:latest
    

    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
