name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * 0'

jobs:

  push:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile -t jfmatth/hugobuilder:latest

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Push image
        run: |
          docker push jfmatth/hugobuilder:latest
